# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c548f25aa37e83b6d9d056a6de63c93b223f94379eb80fc1a356d503ed9b4f966176096aea15616c961166c84fd6b86a36f19d614b8f8b6b94de19146c4ec4

test:
  secret_key_base: df9b452009dcedf8753204cdb1a9fd970d8dd67a84893682dc010dc844deb10db74bdbeae759707816aca91916da0e1ad02be42c8cb5bec5f0b87c892bfe0ef3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: abc123-just-an-example-change-me
